openapi: 3.0.3
info:
  title: Bus App
  description: >-
    # Bus App.app

     Description
    Testing Bus App

  version: 1.3.1
  contact: {}
servers:
  - url: __SERVER_URL__
paths:
  /users/bus-owners:
    get:
      tags:
        - 🔐 Authentication
      summary: Get logged in user
      description: >-
        The API endpoint allows you to retrieve the details of the currently
        logged-in user based on their authentication token.

        When accessing this endpoint with a valid authentication token, you will
        receive a response containing the information of the user who is
        currently authenticated and logged in.
      operationId: getLoggedInUser
      responses:
        '200':
          description: Get logged in user
         
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                   


tags:
  - name: 🚫 Danger Zone
    description: '**WARNING: Sensitive Operations ⚠️**'
